using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace RageRunner {
  public enum WeaponKind { DualPistols, AssaultBlaster, Shotgun, RocketLauncher, PlasmaCannon, LightningGun }
  public enum EnemyKind { Basic, Fast, Tank, Ranged, Exploder, Elite, MiniBoss, MajorBoss }

  public static class SaveSystem {
    public static int Coins { get { return PlayerPrefs.GetInt("rr_coins", 0); } set { PlayerPrefs.SetInt("rr_coins", value); PlayerPrefs.Save(); } }
    public static int BestWave { get { return PlayerPrefs.GetInt("rr_best_wave", 0); } set { PlayerPrefs.SetInt("rr_best_wave", Mathf.Max(BestWave, value)); PlayerPrefs.Save(); } }
    public static int WeaponLevel(WeaponKind w) { return PlayerPrefs.GetInt("rr_weapon_" + (int)w, w == WeaponKind.DualPistols ? 1 : 0); }
    public static bool IsUnlocked(WeaponKind w) { return WeaponLevel(w) > 0; }
    public static bool TryBuyWeapon(WeaponKind w, int cost) { if (Coins < cost) return false; Coins -= cost; PlayerPrefs.SetInt("rr_weapon_" + (int)w, 1); PlayerPrefs.Save(); return true; }
    public static bool UpgradeWeapon(WeaponKind w, int cost) { if (Coins < cost || !IsUnlocked(w)) return false; Coins -= cost; PlayerPrefs.SetInt("rr_weapon_" + (int)w, WeaponLevel(w) + 1); PlayerPrefs.Save(); return true; }
  }

  [Serializable] public class WeaponStats {
    public WeaponKind kind; public string label; public float damage, fireRate, range, splash; public int projectiles;
    public WeaponStats(WeaponKind k, string n, float d, float r, float ra, float s, int p) { kind=k; label=n; damage=d; fireRate=r; range=ra; splash=s; projectiles=p; }
    public static WeaponStats Get(WeaponKind k) {
      switch(k) {
        case WeaponKind.AssaultBlaster: return new WeaponStats(k,"ASSAULT BLASTER",18,8,24,0,1);
        case WeaponKind.Shotgun: return new WeaponStats(k,"SHOTGUN",16,1.8f,15,1.8f,6);
        case WeaponKind.RocketLauncher: return new WeaponStats(k,"ROCKET LAUNCHER",65,.9f,30,3.5f,1);
        case WeaponKind.PlasmaCannon: return new WeaponStats(k,"PLASMA CANNON",95,.55f,32,0,1);
        case WeaponKind.LightningGun: return new WeaponStats(k,"LIGHTNING GUN",38,5,28,2.2f,1);
        default: return new WeaponStats(k,"DUAL PISTOLS",12,6,22,0,2);
      }
    }
  }

  public class RageRunner : MonoBehaviour {
    public static RageRunner I; public PlayerController player; public WaveManager waves; public Canvas canvas; public Text hud, banner; public Slider health, rage; public GameObject menuPanel, upgradePanel, gameOverPanel;
    public int runCoins, kills; public float rageMeter; public bool playing;
    void Awake(){ I=this; Application.targetFrameRate=60; Screen.orientation=ScreenOrientation.LandscapeLeft; BuildScene(); }
    void Start(){ ShowMenu(); }
    void Update(){ if(!playing) return; if(Input.GetKeyDown(KeyCode.Escape)) Pause(); UpdateHUD(); }
    void BuildScene(){
      RenderSettings.ambientLight=new Color(.18f,.2f,.3f); RenderSettings.fog=true; RenderSettings.fogColor=new Color(.04f,.05f,.1f); RenderSettings.fogDensity=.012f;
      var light=new GameObject("Moonlight"); var dl=light.AddComponent<Light>(); dl.type=LightType.Directional; dl.intensity=1.1f; dl.color=new Color(.55f,.7f,1f); light.transform.rotation=Quaternion.Euler(48,-25,0);
      var cam=new GameObject("CombatCamera"); cam.tag="MainCamera"; cam.AddComponent<Camera>(); cam.GetComponent<Camera>().fieldOfView=55; cam.AddComponent<CameraFollow>();
      player=new GameObject("RageRunner_Player").AddComponent<PlayerController>(); player.transform.position=new Vector3(0,0,0);
      waves=new GameObject("WaveManager").AddComponent<WaveManager>();
      BuildUI();
      var road=GameObject.CreatePrimitive(PrimitiveType.Cube); road.name="NeonArena"; road.transform.position=new Vector3(0,-.7f,14); road.transform.localScale=new Vector3(20,1,90); road.GetComponent<Renderer>().material=Mat(new Color(.035f,.05f,.1f));
      for(int i=-4;i<=4;i++){ var strip=GameObject.CreatePrimitive(PrimitiveType.Cube); strip.transform.position=new Vector3(i*2.4f,-.12f,14); strip.transform.localScale=new Vector3(.045f,.04f,90); strip.GetComponent<Renderer>().material=Mat(new Color(.08f,.35f,.8f)); }
    }
    Material Mat(Color c){ var m=new Material(Shader.Find("Standard")); m.color=c; m.EnableKeyword("_EMISSION"); m.SetColor("_EmissionColor",c*1.8f); return m; }
    Text T(string text, Transform p, int size, Color color){ var o=new GameObject("Text"); o.transform.SetParent(p,false); var t=o.AddComponent<Text>(); t.text=text; t.font=Resources.GetBuiltinResource<Font>("Arial.ttf"); t.fontSize=size; t.color=color; t.alignment=TextAnchor.MiddleCenter; return t; }
    void BuildUI(){ var co=new GameObject("UI"); canvas=co.AddComponent<Canvas>(); canvas.renderMode=RenderMode.ScreenSpaceOverlay; co.AddComponent<CanvasScaler>().uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize; co.GetComponent<CanvasScaler>().referenceResolution=new Vector2(1280,720); co.AddComponent<GraphicRaycaster>(); var es=new GameObject("EventSystem"); es.AddComponent<UnityEngine.EventSystems.EventSystem>(); es.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();
      hud=T("",canvas.transform,28,Color.white); hud.rectTransform.anchorMin=new Vector2(0,1); hud.rectTransform.anchorMax=new Vector2(1,1); hud.rectTransform.pivot=new Vector2(.5f,1); hud.rectTransform.anchoredPosition=new Vector2(0,-20); hud.rectTransform.sizeDelta=new Vector2(-40,60);
      banner=T("",canvas.transform,44,new Color(1,.8f,.2f)); banner.rectTransform.anchorMin=new Vector2(.5f,.65f); banner.rectTransform.anchorMax=new Vector2(.5f,.65f); banner.rectTransform.sizeDelta=new Vector2(700,100);
      health=Bar(canvas.transform,new Vector2(0,1),new Color(1,.15f,.18f),new Vector2(260,24),new Vector2(170,-60)); rage=Bar(canvas.transform,new Vector2(0,1),new Color(1,.2f,.05f),new Vector2(260,18),new Vector2(170,-94));
      menuPanel=Panel("RAGE RUNNER",new Color(.03f,.04f,.1f,.96f)); var play=Button("PLAY",menuPanel.transform,new Vector2(0,-75),new Vector2(300,70)); play.onClick.AddListener(StartRun); var info=T("NEON SURVIVAL // BEST WAVE: "+SaveSystem.BestWave+" // COINS: "+SaveSystem.Coins,menuPanel.transform,20,new Color(.5f,.7f,1)); info.rectTransform.anchoredPosition=new Vector2(0,70);
      upgradePanel=Panel("CHOOSE YOUR UPGRADE",new Color(.05f,.03f,.12f,.98f)); gameOverPanel=Panel("RUN ENDED",new Color(.08f,.02f,.05f,.98f));
      Button("RESTART",gameOverPanel.transform,new Vector2(-170,-95),new Vector2(260,62)).onClick.AddListener(StartRun); Button("MENU",gameOverPanel.transform,new Vector2(170,-95),new Vector2(260,62)).onClick.AddListener(ShowMenu);
    }
    Slider Bar(Transform p,Vector2 anchor,Color c,Vector2 size,Vector2 pos){ var o=new GameObject("Bar"); o.transform.SetParent(p,false); var s=o.AddComponent<Slider>(); s.minValue=0;s.maxValue=1;s.value=1;s.interactable=false; s.GetComponent<RectTransform>().anchorMin=anchor;s.GetComponent<RectTransform>().anchorMax=anchor;s.GetComponent<RectTransform>().pivot=new Vector2(0,1);s.GetComponent<RectTransform>().sizeDelta=size;s.GetComponent<RectTransform>().anchoredPosition=pos; var bg=o.AddComponent<Image>(); bg.color=new Color(.05f,.05f,.08f,.9f); var fill=new GameObject("Fill");fill.transform.SetParent(o.transform,false);var im=fill.AddComponent<Image>();im.color=c;s.fillRect=im.rectTransform;im.rectTransform.anchorMin=Vector2.zero;im.rectTransform.anchorMax=Vector2.one;im.rectTransform.offsetMin=Vector2.zero;im.rectTransform.offsetMax=Vector2.zero;return s; }
    GameObject Panel(string title,Color color){ var o=new GameObject(title);o.transform.SetParent(canvas.transform,false);var im=o.AddComponent<Image>();im.color=color;var r=o.GetComponent<RectTransform>();r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;T(title,o.transform,54,new Color(1,.25f,.3f)).rectTransform.anchoredPosition=new Vector2(0,100);o.SetActive(false);return o; }
    Button Button(string label,Transform p,Vector2 pos,Vector2 size){var o=new GameObject(label);o.transform.SetParent(p,false);var b=o.AddComponent<Button>();var im=o.AddComponent<Image>();im.color=new Color(.12f,.25f,.55f,.95f);var r=o.GetComponent<RectTransform>();r.sizeDelta=size;r.anchoredPosition=pos;var t=T(label,o.transform,26,Color.white);t.rectTransform.sizeDelta=size;return b;}
    public void StartRun(){ menuPanel.SetActive(false);gameOverPanel.SetActive(false);playing=true;runCoins=0;kills=0;rageMeter=0;player.ResetForRun();waves.Begin(); banner.text="WAVE 1"; StartCoroutine(ClearBanner()); }
    IEnumerator ClearBanner(){yield return new WaitForSeconds(1.5f);banner.text="";}
    public void ShowMenu(){playing=false;menuPanel.SetActive(true);upgradePanel.SetActive(false);gameOverPanel.SetActive(false);banner.text="";}
    public void GameOver(){playing=false;SaveSystem.BestWave=waves.wave; gameOverPanel.SetActive(true); T("WAVE "+waves.wave+"  •  KILLS "+kills+"  •  COINS "+runCoins,gameOverPanel.transform,28,Color.white).rectTransform.anchoredPosition=new Vector2(0,0); }
    public void AddReward(int c){runCoins+=c;SaveSystem.Coins+=c;rageMeter=Mathf.Min(100,rageMeter+4); if(rageMeter>=100){player.rageMode=true;banner.text="RAGE MODE!";rageMeter=0;StartCoroutine(ClearBanner());}}
    public void UpdateHUD(){if(player==null)return; health.value=player.health/player.maxHealth;rage.value=rageMeter/100f;hud.text="WAVE "+waves.wave+"     COINS "+runCoins+"     KILLS "+kills+"     COMBO x"+player.combo+"     "+WeaponStats.Get(player.weapon).label+"     [SPACE] ability";}
    public void OfferUpgrade(){upgradePanel.SetActive(true); string[] names={"OVERDRIVE  +25% DAMAGE","RAPID CORE  +20% FIRE RATE","ARMOR PLATING  +25% HEALTH","CHAIN ROUNDS  +1 PROJECTILE","RAGE FUEL  +35% RAGE"}; for(int i=0;i<3;i++){int n=UnityEngine.Random.Range(0,names.Length);var b=Button(names[n],upgradePanel.transform,new Vector2((i-1)*300,-10),new Vector2(270,120)); b.onClick.AddListener(()=>{ApplyUpgrade(n);upgradePanel.SetActive(false);waves.ResumeAfterUpgrade();});}}
    void ApplyUpgrade(int n){if(n==0)player.damageMult+=.25f; if(n==1)player.fireMult+=.2f; if(n==2){player.maxHealth*=1.25f;player.health=player.maxHealth;}if(n==3)player.extraProjectiles++;if(n==4)rageMeter=Mathf.Min(100,rageMeter+35);}
    public void Pause(){playing=!playing;banner.text=playing?"":"PAUSED";}
  }

  public class CameraFollow:MonoBehaviour { Transform target; Vector3 vel; void LateUpdate(){if(target==null){var p=GameObject.Find("RageRunner_Player");if(p)target=p.transform;}if(target==null)return;var desired=target.position+new Vector3(0,10,-13);transform.position=Vector3.SmoothDamp(transform.position,desired,ref vel,.12f);transform.LookAt(target.position+Vector3.up*1.2f);}}

  public class PlayerController:MonoBehaviour { public float maxHealth=100,health,damageMult=1,fireMult=1; public int combo,extraProjectiles; public bool rageMode; public WeaponKind weapon=WeaponKind.DualPistols; float shot,side; Vector3 target;
    void Start(){health=maxHealth;CreateBody();} void CreateBody(){var body=GameObject.CreatePrimitive(PrimitiveType.Capsule);body.transform.SetParent(transform);body.transform.localPosition=Vector3.up*1.1f;body.transform.localScale=new Vector3(.7f,1.1f,.7f);body.GetComponent<Renderer>().material=Mat(new Color(.15f,.8f,1));var head=GameObject.CreatePrimitive(PrimitiveType.Sphere);head.transform.SetParent(transform);head.transform.localPosition=new Vector3(0,2.25f,0);head.transform.localScale=Vector3.one*.55f;head.GetComponent<Renderer>().material=Mat(new Color(1,.35f,.2f));} Material Mat(Color c){var m=new Material(Shader.Find("Standard"));m.color=c;return m;}
    public void ResetForRun(){health=maxHealth;transform.position=Vector3.zero;combo=0;rageMode=false;shot=0;} void Update(){if(!RageRunner.I.playing)return;Move();AutoFire();if(Input.GetKeyDown(KeyCode.Space)||Input.touchCount==3)Ability();} void Move(){float x=Input.GetAxis("Horizontal");if(Input.touchCount>0){var t=Input.GetTouch(0);if(t.phase==TouchPhase.Moved)x=t.deltaPosition.x/Screen.width*8;}side=Mathf.Clamp(side+x*Time.deltaTime*5,-7,7);transform.position=new Vector3(side,0,transform.position.z);transform.position+=Vector3.forward*Time.deltaTime*3.5f; if(transform.position.z>25)transform.position=new Vector3(side,0,0);}
    void AutoFire(){shot-=Time.deltaTime;var s=WeaponStats.Get(weapon);float rate=s.fireRate*(1+fireMult);if(rageMode)rate*=1.7f;if(shot<=0){shot=1/rate;Enemy e=WaveManager.Nearest(transform.position,s.range);if(e){for(int i=0;i<s.projectiles+extraProjectiles;i++){var p=Projectile.Get();p.Launch(transform.position+Vector3.up*1.5f,e.transform.position,s.damage*damageMult,s.splash,weapon);}}}}
    public void Damage(float d){health-=d;combo=0;if(health<=0)RageRunner.I.GameOver();} public void Ability(){var e=new List<Enemy>(WaveManager.All());foreach(var x in e)if(x) x.Damage(80*damageMult, true);RageRunner.I.banner.text="NUCLEAR BURST!";StartCoroutine(Clear());} System.Collections.IEnumerator Clear(){yield return new WaitForSeconds(1);RageRunner.I.banner.text="";}}

  public class Projectile:MonoBehaviour {static readonly Queue<Projectile> pool=new Queue<Projectile>();Vector3 dir;float damage,splash,life;WeaponKind kind;public static Projectile Get(){var p=pool.Count>0?pool.Dequeue():new GameObject("Projectile").AddComponent<Projectile>();p.gameObject.SetActive(true);return p;}public void Launch(Vector3 from,Vector3 to,float d,float s,WeaponKind k){transform.position=from;dir=(to-from).normalized;damage=d;splash=s;kind=k;life=2;transform.localScale=Vector3.one*.15f;GetComponent<Renderer>()?.material.SetColor("_Color",Color.cyan);if(GetComponent<Renderer>()==null){var r=gameObject.AddComponent<MeshRenderer>();gameObject.AddComponent<MeshFilter>().mesh=Resources.GetBuiltinResource<Mesh>("Cube.fbx");r.material=new Material(Shader.Find("Standard"));r.material.color=k==WeaponKind.RocketLauncher?Color.red:Color.cyan;}}void Update(){transform.position+=dir*24*Time.deltaTime;life-=Time.deltaTime;if(life<=0)Recycle();foreach(var e in new List<Enemy>(WaveManager.All()))if(e&&Vector3.Distance(transform.position,e.transform.position)<1){e.Damage(damage,true);if(splash>0)foreach(var x in new List<Enemy>(WaveManager.All()))if(x&&x!=e&&Vector3.Distance(x.transform.position,e.transform.position)<splash)x.Damage(damage*.45f,true);Recycle();break;}}void Recycle(){gameObject.SetActive(false);pool.Enqueue(this);}}

  public class Enemy:MonoBehaviour {public EnemyKind kind;public float health,maxHealth,damage,speed;float attack;bool phaseTwo;public void Init(EnemyKind k,int wave){kind=k;float m=1+wave*.12f;maxHealth=health=(k==EnemyKind.MajorBoss?900:k==EnemyKind.MiniBoss?280:35)*m;damage=(k==EnemyKind.Tank?18:k==EnemyKind.MajorBoss?30:7)*m;speed=k==EnemyKind.Fast?5:k==EnemyKind.Tank?1.4f:2.3f;CreateVisual();}void CreateVisual(){var prim=kind==EnemyKind.MajorBoss||kind==EnemyKind.MiniBoss?PrimitiveType.Cube:PrimitiveType.Sphere;var v=GameObject.CreatePrimitive(prim);v.transform.SetParent(transform);v.transform.localPosition=Vector3.up*((int)kind>=(int)EnemyKind.MiniBoss?2:1);v.transform.localScale=Vector3.one*((int)kind>=(int)EnemyKind.MiniBoss?2.5f:kind==EnemyKind.Tank?1.5f:.8f);var m=new Material(Shader.Find("Standard"));m.color=(int)kind>=(int)EnemyKind.MiniBoss?new Color(1,.1f,.4f):kind==EnemyKind.Fast?Color.yellow:new Color(.8f,.1f,.2f);v.GetComponent<Renderer>().material=m;}void Update(){if(!RageRunner.I.playing)return;var p=RageRunner.I.player.transform;transform.position=Vector3.MoveTowards(transform.position,p.position,speed*Time.deltaTime);transform.Rotate(0,80*Time.deltaTime,0);if(Vector3.Distance(transform.position,p.position)<1.5f){attack-=Time.deltaTime;if(attack<=0){attack=.8f;p.GetComponent<PlayerController>().Damage(damage);}}if(kind==EnemyKind.MajorBoss&&health<maxHealth*.5f&&!phaseTwo){phaseTwo=true;speed*=1.5f;RageRunner.I.banner.text="BOSS PHASE 2!";}}public void Damage(float d,bool critical){health-=d;RageRunner.I.rageMeter=Mathf.Min(100,RageRunner.I.rageMeter+2);if(health<=0){RageRunner.I.kills++;RageRunner.I.AddReward((int)kind>=(int)EnemyKind.MiniBoss?100:5);if(kind==EnemyKind.MajorBoss)RageRunner.I.banner.text="BOSS DESTROYED!";WaveManager.Despawn(this);}}}

  public class WaveManager:MonoBehaviour {public int wave;int alive;float spawn;public bool waitingUpgrade;static readonly List<Enemy> enemies=new List<Enemy>();public void Begin(){Clear();wave=0;NextWave();}public void NextWave(){wave++;waitingUpgrade=false;alive=wave<5?new[]{10,20,35,50}[wave-1]:Mathf.RoundToInt(50+wave*12);if(wave%5==0)alive=1;spawn=0;RageRunner.I.banner.text=(wave%10==0?"MAJOR BOSS":"WAVE "+wave);RageRunner.I.StartCoroutine(ClearText());}System.Collections.IEnumerator ClearText(){yield return new WaitForSeconds(1.3f);if(RageRunner.I)RageRunner.I.banner.text="";}void Update(){if(!RageRunner.I.playing||waitingUpgrade)return;if(alive>0){spawn-=Time.deltaTime;if(spawn<=0){spawn=.12f;Spawn();alive--;}}else if(enemies.Count==0){if(wave%3==0){waitingUpgrade=true;RageRunner.I.OfferUpgrade();}else NextWave();}}void Spawn(){EnemyKind k=wave%10==0?EnemyKind.MajorBoss:wave%5==0?EnemyKind.MiniBoss:(EnemyKind)UnityEngine.Random.Range(0,Mathf.Min(6,1+wave/2));var e=new GameObject("Enemy_"+k).AddComponent<Enemy>();e.transform.position=new Vector3(UnityEngine.Random.Range(-7f,7f),0,UnityEngine.Random.Range(24f,38f));e.Init(k,wave);enemies.Add(e);}public void ResumeAfterUpgrade(){NextWave();}public void Clear(){foreach(var e in enemies)if(e)Destroy(e.gameObject);enemies.Clear();}public static void Despawn(Enemy e){enemies.Remove(e);Destroy(e.gameObject);}public static List<Enemy> All(){return enemies;}public static Enemy Nearest(Vector3 pos,float range){Enemy best=null;float d=range;foreach(var e in enemies)if(e&&Vector3.Distance(pos,e.transform.position)<d){best=e;d=Vector3.Distance(pos,e.transform.position);}return best;}}
}
